#!/bin/sh

if [ -z "${IDSTORE_SERVER_HOME}" ]
then
  echo "IDSTORE_SERVER_HOME is unset" 1>&2
  exit 1
fi

if [ -z "${IDSTORE_SERVER_LOG_DIRECTORY}" ]
then
  echo "IDSTORE_SERVER_LOG_DIRECTORY is unset" 1>&2
  exit 1
fi

exec /usr/bin/env java \
-p "${IDSTORE_SERVER_HOME}/lib" \
-m com.io7m.idstore.server.main/com.io7m.idstore.server.main.IdServerMain \
"$@"
