{
 "title": "Idstore",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Metrics", "query": "prometheus" },
   { "name": "instance", "query": { "query": "label_values(idstore_up,job)" } }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "description": "Whether the server is actively serving requests, or is in maintenance mode.",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "idstore_closed_for_maintenance{job=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "LATENCY",
   "type": "timeseries",
   "description": "The average time it has been taking for HTTP requests to complete.",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "idstore_http_time{job=~\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "DELAY",
   "type": "stat",
   "description": "Shows the explicit configured login delays.",
   "gridPos": { "h": 6, "w": 1, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "idstore_ratelimit_login_delay{job=~\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "TRAFFIC",
   "type": "timeseries",
   "description": "The number of requests that are being serviced every second.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(idstore_http_requests_total{job=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "ERRORS",
   "type": "timeseries",
   "description": "The numbers of requests that are ending in some kind of error.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(idstore_http_responses_4xx_total{job=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "4xx"
    },
    {
     "expr": "rate(idstore_http_responses_5xx_total{job=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "SESSIONS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "idstore_sessions{job=~\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "RATE LIMITS",
   "type": "timeseries",
   "description": "The number of occurrences of rate limit violations per second.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum by (operation) (rate(idstore_ratelimit_triggers_total{job=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "DATABASE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CONNECTION TIME",
   "type": "timeseries",
   "description": "The periodically sampled time that database connections are being held open due to transactions in progress.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "idstore_db_connection_time{job=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TRANSACTIONS",
   "type": "timeseries",
   "description": "The number of transactions that are being committed or rolled back every second.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(idstore_db_commits_total{job=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "commits"
    },
    {
     "expr": "rate(idstore_db_rollbacks_total{job=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "rollbacks"
    }
   ]
  },
  {
   "title": "CONNECTIONS",
   "type": "stat",
   "description": "The number of active database connections in relation to the total number of available connections. 100% usage means that clients will be waiting for connections to become available.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  { "title": "MAIL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "SENDS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(idstore_mail_ok_total{job=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "ERRORS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(idstore_mail_failed_total{job=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "DURATIONS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "idstore_mail_time{job=~\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}