#!/bin/sh

if [ -z "${IDSTORE_ADMIN_HOME}" ]
then
  echo "IDSTORE_ADMIN_HOME is unset" 1>&2
  exit 1
fi

exec /usr/bin/env java \
-p "${IDSTORE_ADMIN_HOME}/lib" \
-m com.io7m.idstore.admin_gui.main/com.io7m.idstore.admin_gui.main.IdAGMain \
"$@"
